name: JS

on: push

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build_js:
    strategy:
      fail-fast: true
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      VITE_CONDUIT_KEY: ${{ secrets.VITE_CONDUIT_KEY }}

    name: Build js package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Install node deps and founry
        uses: ./.github/actions/setup_deps

      - name: Build js package
        run: |
          pnpm turbo run build

      - name: Test js package
        run: |
          pnpm turbo run test:js
